USE SkyTracke;

ALTER TABLE Flight
ADD airline_id INT NULL;

ALTER TABLE Flight
ADD gate_id INT NULL;

UPDATE Flight SET airline_id = 1 WHERE airline_id IS NULL;

ALTER TABLE Flight
ALTER COLUMN airline_id INT NOT NULL;

ALTER TABLE Flight
ADD CONSTRAINT FK_Flight_Airline
    FOREIGN KEY (airline_id) REFERENCES Airline(airline_id)
    ON DELETE NO ACTION
    ON UPDATE CASCADE;

ALTER TABLE Flight
ADD CONSTRAINT FK_Flight_Gate
    FOREIGN KEY (gate_id) REFERENCES Gate(gate_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE;


SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Flight'
ORDER BY ORDINAL_POSITION;
